version: "3"

services:
  mongodb:
    image: mongo:4.2.18
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    hostname: mongodb-server
    environment:
      - MONGO_INITDB_DATABASE=admin

  metabase:
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./data/metabase:/metabase-data
    depends_on:
      - mongodb
